version: '{build}'
image: 'Visual Studio 2017'

clone_folder: 'c:\go\src\github.com\appleboy\drone-telegram'

environment:
  GOPATH: c:\go
  docker_username:
    secure: em/TNLUXxG19O/HvbvfJuQ==
  docker_password:
    secure: Yo9FJJqihaNz5q8T4Jz8tQ==

branches:
  only:
    - master

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - docker version

build_script:
  - ps: |
      go build .
      docker pull microsoft/nanoserver:10.0.14393.1884
      docker build -f Dockerfile.windows -t appleboy/drone-telegram:windows .

test_script:
  - ps: |
      docker run --rm appleboy/drone-telegram:windows --version

deploy_script:
  - ps: |
      docker login --username $env:DOCKER_USERNAME --password $env:DOCKER_PASSWORD
      docker push appleboy/drone-telegram:windows
